"""
ECC-specific features — real-world example of domain-specific extras.

Derived from ECC (Enterprise Coding Conventions), a 117-rule coding standard
framework across 21 languages. ECC is a separate project maintained by the
neuro-skill author, available at ~/.claude/rules/ecc/.

Generated by hand from 314 ECC skills (agent, content, security, infra,
mobile, frontend, backend, testing, devops, video, compliance, data-science,
blockchain, network domains).

Process:
  1. Traverse all 314 skill names + descriptions to identify actual domains
  2. Write discriminative keywords for each domain
  3. merge_features(base, auto={}, user=ECC_features) → 94 total features

Result on 314 ECC skills:
  - Hit@1: 21% (base only) → 65% (base + ECC extras)
  - Hit@3: 32% → 77%
  - Hybrid first significantly outperforms keyword at this scale

This file is the second reference extras after extras_template.py.
Copy the pattern for your own domain.
"""

# 16 coarse domain categories found in ECC skill set
ECC_BROAD = {
    "agent-autonomous": [
        "supergoal", "autonomous", "agent", "supervisor", "orchestrator",
        "multi-agent", "自主", "自动化", "代理",
    ],
    "content-creation": [
        "article", "content", "writing", "brand", "copywriting", "文案",
        "内容", "写作", "品牌",
    ],
    "research-intelligence": [
        "research", "deep research", "market research", "intelligence",
        "调研", "研究", "深度研究",
    ],
    "mobile-development": [
        "flutter", "react native", "swift", "kotlin", "ios", "android",
        "mobile", "移动", "跨平台",
    ],
    "security-audit": [
        "security", "vulnerability", "audit", "owasp", "penetration",
        "安全", "漏洞", "审计", "渗透",
    ],
    "infrastructure-cloud": [
        "docker", "kubernetes", "terraform", "azure", "aws", "cloud",
        "infrastructure", "容器", "云", "部署",
    ],
    "database-storage": [
        "database", "postgres", "mysql", "redis", "sql", "migration",
        "schema", "query", "clickhouse", "数据库", "存储",
    ],
    "frontend-ui": [
        "react", "vue", "angular", "tailwind", "css", "ui", "component",
        "前端", "界面", "组件",
    ],
    "backend-api": [
        "django", "fastapi", "springboot", "quarkus", "api", "rest",
        "graphql", "backend", "后端", "接口",
    ],
    "testing-qa": [
        "test", "e2e", "tdd", "coverage", "playwright", "pytest",
        "测试", "覆盖率", "端到端",
    ],
    "devops-ci": [
        "github actions", "ci/cd", "pipeline", "deploy", "build",
        "部署", "构建", "流水线",
    ],
    "video-media": [
        "video", "editing", "media", "mp4", "gif", "animation",
        "视频", "剪辑", "媒体",
    ],
    "enterprise-compliance": [
        "hipaa", "compliance", "enterprise", "audit", "合规", "企业",
    ],
    "data-science-ml": [
        "machine learning", "data science", "pytorch", "training",
        "model", "机器学习", "数据科学", "训练",
    ],
    "blockchain-web3": [
        "defi", "blockchain", "web3", "smart contract", "crypto",
        "区块链", "智能合约",
    ],
    "network-infra": [
        "network", "dns", "routing", "firewall", "homelab", "vpn",
        "网络", "路由", "防火墙", "家庭网络",
    ],
}

# 45 fine-grained matchers for specific ECC skills
ECC_PRECISE = {
    # Backend frameworks
    "django": ["django", "drf", "orm", "queryset", "django-admin"],
    "fastapi": ["fastapi", "pydantic", "async", "dependency injection"],
    "springboot": [
        "springboot", "spring-boot", "springboot-patterns",
        "springboot-security", "springboot-tdd",
    ],
    "quarkus": ["quarkus", "quarkus-security", "quarkus-patterns"],
    "kotlin": ["kotlin", "coroutines", "kotlin-flows", "kotlin-patterns"],
    # Mobile
    "flutter": ["flutter", "widget", "dart", "bloc", "provider"],
    "swift": ["swift", "swiftui", "xcode", "ios"],
    "react-native": ["react native", "react-native", "expo"],
    # Backend languages
    "golang": ["golang", "goroutine", "go-patterns", "go-tdd"],
    "rust": ["rust", "cargo", "tokio", "serde", "rust-patterns"],
    # Databases
    "postgres": ["postgres", "postgresql", "pg", "psql"],
    "redis": ["redis", "cache", "key-value", "pub-sub"],
    "mysql": ["mysql", "innodb", "myisam"],
    "clickhouse": ["clickhouse", "olap", "columnar"],
    # Infrastructure
    "docker": ["docker", "dockerfile", "container", "docker-compose"],
    "kubernetes": ["kubernetes", "k8s", "helm", "pod"],
    "terraform": ["terraform", "iac", "hcl", "terraform-plan"],
    "azure": ["azure", "microsoft cloud", "azure-functions"],
    # Frontend
    "react": ["react", "jsx", "hooks", "nextjs", "react-patterns"],
    "vue": ["vue", "vuex", "pinia", "nuxt"],
    "angular": ["angular", "ng", "rxjs", "angular-components"],
    # A11y & Design
    "a11y": ["accessibility", "a11y", "wcag", "screen-reader", "aria"],
    "motion": ["animation", "motion", "framer-motion", "gsap"],
    # E2E testing
    "e2e": ["e2e", "playwright", "cypress", "selenium", "end-to-end"],
    # Content
    "content-engine": ["content", "article", "blog", "copy"],
    "article-writing": ["article", "writing", "blog-post", "长文"],
    "brand-voice": ["brand", "voice", "tone", "品牌", "调性"],
    # Research
    "deep-research": ["deep research", "adversarial", "multi-source"],
    "market-research": ["market", "competitor", "industry", "市场"],
    "investor": ["investor", "pitch", "deck", "fundraising", "融资"],
    # Security
    "security-scan": ["security scan", "vulnerability scan", "cve"],
    "security-review": ["security review", "audit", "penetration"],
    "owasp": ["owasp", "top-10", "xss", "csrf", "injection"],
    "hipaa": ["hipaa", "healthcare", "phi", "medical-compliance"],
    # Blockchain
    "defi": ["defi", "blockchain", "solidity", "web3", "smart-contract"],
    # CI / CD
    "github-actions": ["github actions", "workflow", "action", "ci"],
    "git-workflow": ["git", "commit", "branch", "merge", "conventional"],
    # Patterns
    "api-design": ["api design", "rest", "graphql", "openapi"],
    "error-handling": ["error", "exception", "retry", "fallback"],
    "migration": ["migration", "schema change", "flyway", "alembic"],
    # Org / Process
    "council": ["council", "decision", "architecture decision"],
    "homelab": ["homelab", "self-hosted", "home server", "nas"],
    # Data
    "scrape": ["scrape", "crawl", "firecrawl", "web scraping"],
    # ECC native rules
    "ecc-native": [
        "ecc", "coding standard", "编码规范", "hooks配置",
        "git-workflow", "code-review", "testing-guide", "security-guide",
        "ecc-rule", "ecc配置",
    ],
}
